### ISSUE TITLE
Tags for versions 1.2.2 to 1.2.7 are missing

### ISSUE THREAD

**Issue by devurandom** [jselbie/stunserver#14]
The tags for releases in this repository stop at version 1.2.1, while version 1.2.7 is current. It would be great if they could be added.

**Comment by jselbie** [comment]
I don't find too much excitement in fixing this. Most of those point releases were bug fixes and/or fixing compiler issues on different platforms.

You can find snapshots of each version release on the corresponding [SourceForge page here](http://sourceforge.net/projects/stuntman/files/?source=navbar)  

The [HISTORY](https://github.com/jselbie/stunserver/blob/master/HISTORY) file in the root of the repo lists what each point release was.

**Comment by devurandom** [comment]
The exciting part is that tags make it easier to figure out which patches/commits fixed which issues in which release. That helps in knowing which issues exist in any version and how they were fixed, without having to monitor and guess from the HISTORY file, mailinglist reports or GitHub issues.
