### ISSUE TITLE
Possible bug in client when using IPv6

### ISSUE THREAD

**Issue by danielyli** [jselbie/stunserver#17]
Stuntman version: 1.2.9

When specifying IPv6 using the client, I get an `Unable to resolve hostname` error:

    $ stunclient --family 6 stun.stunprotocol.org
    Unable to resolve hostname for stun.stunprotocol.org
    Can't start client
    Usage: stunclient [OPTIONS] server [port]
    Try 'stunclient --help' for a complete set of options and description of
    paramters

Am I using the flag wrong?

**Comment by jselbie** [comment]
The hosting provider for stun.stunprotocol.org does not support IPv6.

**Comment by jselbie** [comment]
The client and server code both support IPv6.  And if the hosting provider for stun.stunprotocol.org did support IPv6, then what you typed would have worked.

**Comment by danielyli** [comment]
You're right; using a STUN server that supports IPv6, such as `numb.viagenie.ca`, works.  Thanks.
