### ISSUE TITLE
Docker image

### ISSUE THREAD

**Issue by steevehook** [jselbie/stunserver#23]
Hi man, I really like this implementation and it works quite nice as opposed to others I found. The support is not so big but this one looks quite promising, SO BIG THANKS.

However it would be even more interesting to dockerize it. I can help with the image if you need

I got something here, let me know if it helps or needs to be adjusted:
`https://github.com/steevehook/webrtc-conference-stun`

Also created a PR on this, glad to contribute

**Comment by jselbie** [comment]
_"The support is not so big"_

Man, I don't know whether to laugh or cry.  I've gone **over the top** in supporting everyone over the years by respond to nearly every email in my inbox and [mailing list](https://groups.google.com/forum/#!forum/stunprotocol). And by making it as easy as possible to compile and run for all scenarios.

In any case Steve, it is nice to meet you.  And I appreciate your Dockerfile contribution. I'll leave some comments on your PR.  If you can also include your documentation change into resources/readme.src, that would be great.

jselbie

**Comment by steevehook** [comment]
Sounds cool man. I mean I looked a while for a good implementation which works fine with my signalling server and this is the best I found. The rest where either not functioning because of poor docs and/or not properly implemented, I am glad I can contribute to open source, this is my first contribution so I'll be glad to apply the necessary changes in the PR
