### ISSUE TITLE
How to make Direct Peer-to-Peer Communication using Obtained Mapped IP:Port

### ISSUE THREAD

**Issue by mail2chromium** [jselbie/stunserver#29]
@jselbie Kindly visit the below link, i have integrated a lot of stuff but seems like Peer-to-Peer Communication is not being established using **Mapped Addresses** obtained from STUNTMAN Server.

https://stackoverflow.com/questions/58525874/direct-peer-to-peer-communication-using-mapped-or-public-ipport

**Comment by jselbie** [comment]
It doesn't sound like you are doing the hole punching step:

Read this: https://stackoverflow.com/a/8524609/104458
