### ISSUE TITLE
MS Teams STUN support ? 

### ISSUE THREAD

**Issue by huaraz** [jselbie/stunserver#36]
I tested the client against what I think are the MS Teams STUN servers (i.e. I see UDP comm on port 3478) , but did not get any response. 

Does MS use a modified standard ? 

Thank you
Markus

**Comment by jselbie** [comment]
I do not know.

If you run a wireshark trace with the Teams client, what do the packets
look like going to port 3478?  Does wireshark tag them as STUN ?

**Comment by huaraz** [comment]
Yes it does show up as STUN in wireshark.

[Teams-STUN.zip](https://github.com/jselbie/stunserver/files/4999483/Teams-STUN.zip)

**Comment by jselbie** [comment]
It appears to me that they have a couple of non-standard attributes they use in their STUN messages.
