### ISSUE TITLE
stunclient "Unable to create local socket for TCP connection (hr == 8800000d)"

### ISSUE THREAD

**Issue by hxr404** [jselbie/stunserver#37]
Hello,
I downloaded the Windows Builds and ran the command `stunclient --proto tcp --localport 25577 stun.stunprotocol.org`
and it only displays the error message: `Unable to create local socket for TCP connection (hr == 8800000d)`

If I choose another localport or udp as protocol, than I don't get the error message, it displays the ips. How can I fix it? What did I wrong?

Thanks for your help and for this awesome tool.

**Comment by jselbie** [comment]
I'm guessing because another app has that port locked.  That's just a
guess.  Error code d (13) is "permission denied".

Type this at an elevated command prompt:

netstat -b -a -n > out.txt
notepad out.txt

Within notepad, search (CTRL+F) for a socket using that port by searching
for this string

      :25577

The application that is already using that port will be listed on the line
below it.

It's unusual, but not unwarranted, to use stunclient from a specific local
port. What are you really trying to do?

jrs

**Comment by hxr404** [comment]
Thanks for the quick help. Here's the Output from the search:
```
 Es konnten keine Besitzerinformationen abgerufen werden.
  TCP    0.0.0.0:25577          0.0.0.0:0              ABH™REN
 [java.exe]
```
```
 Es konnten keine Besitzerinformationen abgerufen werden.
  TCP    [::]:25577             [::]:0                 ABH™REN
 [java.exe]
```

I try to run a minecraft bungeecord server without portforwarding. Is it even possible? or did I missunderstand something?
I used ngrok, but I want something that also supports udp (and is'nt a proxy). Udp is the most important part, but at the moment I don't have a Minecraft Bedrock (udp) Client to test, so I first wanted to chek how it works with Minecraft Java (tcp). 

When I ran the test, the clients weren't on, only the server, so the problem is with the Server.

**Comment by jselbie** [comment]
So minecraft appears to have a lock on TCP port 25577.  I thought the
client would use SO_REUSEADDR mode, but it doesn't appear to work for TCP
sockets. Not sure whey.

Even if you did obtain a port mapping with stunclient, it's questionable if
anyone else would be able to send UDP to that port without first doing a
coordination with another external server.  Your NAT will basically
firewall any inbound UDP that you didn't first send outbound UDP to first.

What if your network configuration?  Is it just a home residential NAT?
What's wrong with port forwarding?

**Comment by hxr404** [comment]
Its a standart home router (fritz box)
I don't want to use port forwarding, because I thought I could make it portable...

I thought, that the program finds an IP & Port, wich can bypass the NAT, so it can be used similar to ngrok, just with an complete different working principle. Or did I get it wrong?

And what do you mean with "_client would use SO_REUSEADDR mode_" (my english is **really** bad...)

**Comment by jselbie** [comment]
I had forgotten about the `--reuseaddr` option on the command line. In any case, it is not a good idea to to share a port with a different application serving up another protocol.
