### ISSUE TITLE
New official release before Debian 11 freeze

### ISSUE THREAD

**Issue by Neustradamus** [jselbie/stunserver#38]
Hello @jselbie,

The last version is 1.2.13 (13 Mar 2017), it is possible to release a new build before the Debian 11 freeze (2021-01-12)?

And look to update: https://salsa.debian.org/pkg-voip-team/stunserver?
cc: @linuxmaniac

**Comment by jselbie** [comment]
All that needs to be done is copy the code from the github repo ( https://github.com/jselbie/stunserver - master repo)  to the Debian repo. It should build the same way.

What would you like me to do?  I can do a Pull Request to your repo.  Does that work?

**Comment by Neustradamus** [comment]
@jselbie: Thanks for your reply!
- https://salsa.debian.org/pkg-voip-team

Can you send an email to pkg-voip-maintainers@lists.alioth.debian.org?

**Comment by linuxmaniac** [comment]
stunserver was removed from sid https://tracker.debian.org/news/1024931/removed-127-11-from-unstable/ (27 Jan 2019)

**Comment by Neustradamus** [comment]
@linuxmaniac: Yes I know, it can be added no?
@jselbie can enter in the team no?

**Comment by jselbie** [comment]
I'm leaving this closed for now.  It's up to the Debian community if they want to ship Stuntman. Let know how I can help.
