### ISSUE TITLE
Turn server

### ISSUE THREAD

**Issue by chrisooo3** [jselbie/stunserver#40]
Hi @jselbie 
I have symmetric NAT, so I have to use the TURN server. 
Does your program support the TURN server? 
If no, do you have an idea how can I use it to connect p2p with another pc in a different network behind which is also behind NAT? 

Basically, I want to connect two devices that are in different networks and are behind NAT.

**Comment by jselbie** [comment]
Stuntman is STUN only.  If you need relay support that TURN provides,
consider CoTurn. https://github.com/coturn/coturn

You can read my writeup on the basics of the ICE methodology and settings
up a P2P connection here: https://stackoverflow.com/a/8524609/104458

**Comment by flash91120** [comment]
good
