### ISSUE TITLE
hello jselbieHow does the logic of judging the nat type have only one server address in the parameter of stunclient?

### ISSUE THREAD

**Issue by gengfeipeng** [jselbie/stunserver#45]
hello jselbie 
client:
     gengfeipeng@bogon stunserver % ./stunclient --mode full --localaddr 10.2.2.63 --localport 9999 --protocol udp --verbosity 2 117.50.10.29
Resolved 117.50.10.29 to 117.50.10.29:0
config.fBehaviorTest = true
config.fFilteringTest = true
config.timeoutSeconds = 0
config.uMaxAttempts = 0
config.addrServer = 117.50.10.29:3478
socketconfig.addrLocal = 10.2.2.63:9999
Sending message to 117.50.10.29:3478
Got response (68 bytes) from 117.50.10.29:3478 on interface 10.2.2.63:9999
Other address is 117.50.10.29:3479

Preparing message for filtering test #2 (ChangeRequest=AA)
Sending message to 117.50.10.29:3478
Continuing to wait for response...
Continuing to wait for response...
Continuing to wait for response...
Continuing to wait for response...
Continuing to wait for response...
Preparing message for filtering test #2 (ChangeRequest=AA)
Sending message to 117.50.10.29:3478
Continuing to wait for response...
Continuing to wait for response...
Continuing to wait for response...
Continuing to wait for response...
Continuing to wait for response...
Preparing message for filtering test #3 (ChangeRequest=PA)
Sending message to 117.50.10.29:3478
Continuing to wait for response...
Continuing to wait for response...
Continuing to wait for response...
Continuing to wait for response...
Continuing to wait for response...
Preparing message for filtering test #3 (ChangeRequest=PA)
Sending message to 117.50.10.29:3478
Continuing to wait for response...
Continuing to wait for response...
Continuing to wait for response...
Continuing to wait for response...
Continuing to wait for response...
Preparing message for behavior test #2 (destination=AP)
Sending message to 117.50.10.29:3478
Got response (68 bytes) from 117.50.10.29:3478 on interface 10.2.2.63:9999
Binding test: success
Local address: 10.2.2.63:9999
Mapped address: 106.120.244.138:32530
Behavior test: success
Nat behavior: Endpoint Independent Mapping
Filtering test: success
Nat filtering: Address and Port Dependent Filtering

server:
      ./stunserver --mode full --primaryinterface 10.19.99.42 --altinterface 10.19.179.125 --primaryadvertised 117.50.10.29 --altadvertised 106.75.116.8
stunclient recieve len 800
stunclient recieve len 800
stunclient recieve len 800
stunclient recieve len 800
stunclient recieve len 800
stunclient recieve len 800

This is my entire process. What do you think is the reason why I can't send a message to the server's alternate ip?

_Originally posted by @gengfeipeng in https://github.com/jselbie/stunserver/issues/44#issuecomment-998560739_

**Comment by gengfeipeng** [comment]
How does the 5780 5389 version of the stun protocol switch?

**Comment by jselbie** [comment]
When you run a filtering test, the client does not actually send a message to your server's alternate IP.  Instead, it sends a (UDP) request to the server's primary address with a header asking the server to reply **from** its alternate ip or port.  The point of the filtering test is to see how much permissive the NAT is with regards to allowing incoming packets from alternate ip/port pairs.  Some NAT's, upon seeing an outbound UDP packet to a server, allow for UDP responses to come back from "same IP, but different port". Theoretically, a NAT could also allow a response to come back from a "different IP, but same port" - although that would be unusual. And if there was no NAT involved at all, responses could come back from any IP/port pair (although your local firewall software, such as the Windows Firewall, might influence this).

Most all NATs, will only allow responses from "same ip and same port". Hence, all those, "Continuing to wait..." and retry attempts you see in the stunclient output are completely normal and expected.  The Filtering test is just confirming you have a normal NAT with typical firewall behavior.  If the filtering tests is **Address and Port Dependent Filtering**, this is completely normal.

Notice the behavior test above is succeeding in sending a message to your server's alternate IP

```
Preparing message for behavior test #2 (destination=AP)
Sending message to 117.50.10.29:3478
Got response (68 bytes) from 117.50.10.29:3478 on interface 10.2.2.63:9999
Binding test: success
Local address: 10.2.2.63:9999
Mapped address: 106.120.244.138:32530
Behavior test: success
Nat behavior: Endpoint Independent Mapping
```

The behavior test is validating that your NAT is not symmetric.  That's what Endpoint Independent Mapping means.  If it had said "address dependent **mapping**", then you could infer your NAT was likely symmetric. But in your case, it does not. It says "Endpoint Independent Mapping" which basically means, "If you use the same local port, the NAT will likely use the same mapped port".

For what it's worth - and this is just my opinion, But when building up a P2P or VOIP system, NAT classifications are largely unneeded. About the only thing they are useful for is debugging a failed connection.

**Comment by jselbie** [comment]
One thing that appears unusual in your output.  You indicate you start your server as follows:

`./stunserver --mode full --primaryinterface 10.19.99.42 --altinterface 10.19.179.125 --primaryadvertised 117.50.10.29 --altadvertised 106.75.116.8`

In other words, your primary IP is `117.50.10.29` and your alternate ("other") IP is `106.75.116.8`

Yet, your response packet is showing something that doesn't match;

Sending message to 117.50.10.29:3478
Got response (68 bytes) from 117.50.10.29:3478 on interface 10.2.2.63:9999
**Other address is 117.50.10.29:3479**

I don't know why your alternate address is coming back the same as your primary address?

**Comment by gengfeipeng** [comment]
Regarding the problem that my backup address is the same as my main address, my configuration is negligible, thank you for your answer, I understand jselbie.
