### ISSUE TITLE
test questions

### ISSUE THREAD

**Issue by gengfeipeng** [jselbie/stunserver#46]
Why the detected filter types are all AddressAndPortDependentFiltering, but the map detection has EndpointIndependentMapping and AddressAndPortDependentMapping types. Is there anything to pay attention to in filter detection?

**Comment by jselbie** [comment]
The Behavior test measures how predictable the port mapping is with respect
to source address  (ip and port) to destination address.  Most well behaved
NATs will have Endpoint Independent Mapping - meaning that the same
external port is used to map to the internal ip:port pair regardless of
what remote address is used.

Some NAT environments (whether a result of a NAT device or the ISP) are
Address and Port dependent mapping - which means the port mapping is
difficult to predict. Subsequent P2P or VOIP calls may need a relay server.

The Filtering test measures how open the device can be reached from
addresses and ports it did not originally send to.  Given that most NATs
act as firewalls in addition to the PC having its own local firewall,
incoming packets are simply dropped if there was not any corresponding
outbound packet sent to the remote address it originated from.  Hence,
unless you've turned off your PC's firewall and connect it directly to the
internet (without a NAT), you are almost guaranteed to have Address and
Port Dependent Filtering.

Does that make sense? I can elaborate more if needed.

For what it's worth, I don't find the Behavior and Filtering tests
particularly useful for establishing connectivity with another
endpoint. They are best used to simply log the NAT type so you can debug
the reasons for a failed connectivity failure later.
