### ISSUE TITLE
NEW ERROR

### ISSUE THREAD

**Issue by zwfengineer** [jselbie/stunserver#47]
![image](https://user-images.githubusercontent.com/33892516/169929365-8aa38f01-d10f-47a2-b87a-9712ab71642b.png)

**Comment by jselbie** [comment]
It seems like you are compiling with OpenSSL 1.1 or later. This code needs OpenSSL 1.0.2.

The workaround would be download, compile, and install locally OpenSSL from https://github.com/openssl/openssl/ and switch to the 1.0.2.-stable branch.  Build and compile that locally.

In the root of your Stunserver code repo is a file called common.inc. You can uncomment the line near the top to specify your INCLUDE path for OpenSSL 1.0.2.

Does that help?

**Comment by jselbie** [comment]
Also, if you can let me know which OS or Linux distro this was, I'll try to replicate it locally.

**Comment by jstikr** [comment]
@zwfengineer - **ping**

I tried compiling the code with OpenSSL 1.1.1 and it still compiles files.  Can  you please give more details on your configuration such as the exact OS, Linux distro, or anything special about how you installed OpenSSL?

**Comment by jselbie** [comment]
@zwfengineer - last ask to provide more details of your environment before I close out the issue.
