### ISSUE TITLE
Migration to GitHub is not complete

### ISSUE THREAD

**Issue by Neustradamus** [jselbie/stunserver#52]
Dear @jselbie,

It will be nice to remove old parts like:
- https://sourceforge.net/p/stuntman/discussion/

Can you add a "move" box like https://sourceforge.net/projects/handbrake for example.
- https://sourceforge.net/p/stuntman/

To disable/delete tabs, go here: https://sourceforge.net/projects/stuntman/
To add a new tab, go here: https://sourceforge.net/projects/stuntman/
To change informations, go here: https://sourceforge.net/p/stuntman/admin/overview
To export, go here: https://sourceforge.net/p/stuntman/admin/export

The new place can be added in:
- "Moved Project to", here: https://sourceforge.net/p/stuntman/admin/overview
- A new tab, go here: https://sourceforge.net/projects/stuntman/

Thanks in advance.

**Comment by jselbie** [comment]
Please go away.

**Comment by jselbie** [comment]
@Neustradamus  - let me clarify what I meant. I realize I came across as curt in one of my earlier responses.

First, are you a bot?  

In the last few days you've resurrected a handful of issues and threads that I have not felt important enough to pursue.  Commitment to tagging and migrating away from Sourceforge are very low on my priority list right now.

I would like the next refresh of the code base will be in these areas:

* Update the code to modern C++ (preferably C++ 14 or later)
* Review OpenSSL support and OpenSSL version. Consider DTLS if it can be done at scale if WebRTC supports it.
* Improve the multi-threading support
* Review compliance with latest RFCs and continued compatibility with WebRTC.
* Maybe consider CMake or Autotools

But all of this is on the backburner right now. Maybe later this year, I will have time to return to improving the code.

I continue to support this code by making sure that it can still build and run on modern Linux/Unix systems with minimal effort. (e.g. type "make"). If there's ever an issue such that the code doesn't build, deploy, and run, I would bend over backwards to help someone with such an issue.

**Comment by Neustradamus** [comment]
@jselbie: Thanks for your answer!
You are not the first guy like curt badly but the first one who has the honesty to explain himself.

Why a bot?
I have already spoken with you previously no?
- https://github.com/jselbie/stunserver/issues?q=is%3Aissue+author%3ANeustradamus+

I really appreciate your response, thanks for your details, hope you can improve the code, and maybe you can look Meson too.
