### ISSUE TITLE
How to make stunserver differentiate between the listening IP and the external IP

### ISSUE THREAD

**Issue by asbai** [jselbie/stunserver#53]
We have an AWS EC2 instance running stunserver. Its internal IP1 is 172.31.1.1, corresponding to the public (external) IP1 of 1.1.1.1 (BINAT), and internal IP2 is 172.31.2.2, corresponding to the public (external) IP2 of 2.2.2.2 (also through aws igw binat).

Now, using the command stunserver --mode full --primaryinterface 172.31.1.1 --altinterface 172.31.2.2, we can start the Stuntman server. However, due to its lack of awareness of its actual public (external) IP address, there are some issues when communicating with the STUN client. It requires the STUN client to send messages to the internal 172.31 subnet.

Is there any parameter that we haven't discovered yet, which can be used to inform stunserver of the external public IP addresses corresponding to its primary and secondary listening addresses?

Thanks :-)

**Comment by jselbie** [comment]
You want to set the "advertised addresses". There is a pair of parameters
for that: --primaryadvertised and --altadvertised

Example:

stunserver --mode full  --primaryinterface 172.31.1.1 --altinterface
172.31.2.2 --primaryadvertised 1.1.1.1 --altadvertised 2.2.2.2

**Comment by jselbie** [comment]
`stunserver --mode full  --primaryinterface 172.31.1.1 --altinterface 172.31.2.2 --primaryadvertised 1.1.1.1 --altadvertised 2.2.2.2`
