### ISSUE TITLE
Doesn't continue building the server

### ISSUE THREAD

**Issue by Nirmeen23** [jselbie/stunserver#55]
Hello, I executed make command but it lags after this function 
![Screenshot (176)](https://github.com/jselbie/stunserver/assets/97000504/126e5e0c-a6b3-4d0e-b34e-3ba7288c9be1)
I'm using amazon linux
Do you have any solution?

**Comment by jselbie** [comment]
Hi @Nirmeen23  - I'm not able to reproduce this.  I probably need to know two things:

I suspect this is a conflict with your version of boost and your compiler. Sometimes older versions of boost conflict with newer compilers and the easy fix is to just manually point the Stunserver build to a more recent version.

What compiler version are you using?  Can you type `g++ -version` and let me know what you are running?

Do you know what version of boost you have installed?  You can type the following:

```
cd /usr/include/boost
grep BOOST_LIB_VERSION version.hpp
```

That will reveal the version you have installed.  I have both 1.53 installed locally as well as a manual install of 1.83. Both work fine and all versions in between are known to work.

This should fix your issue:

* Download boost from www.boost.org and unpack into a folder

```
curl https://boostorg.jfrog.io/artifactory/main/release/1.83.0/source/boost_1_83_0.tar.gz -o boost.tgz -L
tar xzvf boost.tgz
```

This should create a `boost_1_83_0` folder in the same directory

* Then update your common.inc file in the root and change this line:

`#BOOST_INCLUDE := -I/home/jselbie/boost_1_72_0`

To be uncommented (drop the #) and set the path to your local copy to something like this

`BOOST_INCLUDE := -I/path/to/your/boost/boost_1_83_0`

Then `make clean` followed by `make` again and see if that fixes anything.

Can you try that?

**Comment by jselbie** [comment]
Also, I see you are typing `make` from the server directory. For purposes of the above instructions, type `make clean` and `make` from the root of the repo.

**Comment by jselbie** [comment]
Closing due to lack of response.
