### ISSUE TITLE
STUNSERVER binary sleeping from within a container

### ISSUE THREAD

**Issue by allanbbs** [jselbie/stunserver#56]
Hey, I checked both the provided docker image and a custom on that i did, the process entes the SLEEPING status, and it doenst start properly. The only log printed is "Starting server 1". kill -0 1 awakes the process but the container exits. I tested running the server with the same args in the host machine without docker and it works fine.

Steps to reproduce:
Start stunserver as entrypoint from within a docker, enter the container and check process status. As I said earlier, I tested it with https://hub.docker.com/r/akiroz/stunserver and the following dockerfile:
-----
FROM alpine:latest
WORKDIR /usr/src/app
COPY ./ ./
RUN apk add git
RUN apk add g++
RUN apk add boost-dev
RUN apk add openssl-dev
RUN apk add make
RUN git clone https://github.com/jselbie/stunserver.git stun/
WORKDIR /usr/src/app/stun
RUN make
CMD ["./stunserver", "--primaryinterface", "0.0.0.0","--primaryport", "7001", "--verbosity", "3"]
EXPOSE 7001
------ 

Is this something that is expected currently, or am I missing something here?
PS: I also tested with specific interfaces, so I dont think the problem resides there either. Also, im not expecting customer support here,  I just found it odd. Would rather use this since it works well for my purposes than learning to configure coturn :(

**Comment by jselbie** [comment]
Unfortunately, I do not know much about Docker.

The only think I see on your command line is that you shouldn't explicitly pass 0.0.0.0 as the primary interface. That's the default.  But that's probably not the issue.

Does stunserver print anything out as a result of passing `--verbosity 3` ?  What access do you have to inspecting logs on the container? (I'm wondering if you can redirect the stunserver output to file and inspect it later if you can't see it in real time).

**Comment by jselbie** [comment]
I'm not sure if this matters, but does CMD automatically run its target in the background?  I don't see an ampersand in that command...

**Comment by jselbie** [comment]
Should it be ENTRYPOINT instead of CMD?

**Comment by allanbbs** [comment]
Hello. It turned out to be a caching issue from my side, container was badly configured, and it was not flushing logs as expected. Once this was fixed, the error logs appeared as expected. 
As a side note, both ENTRYPOINT and CMD can be used in docker to start long running processes. In this particular case, those two are interchangeable.

My mistake for opening this issue after all. Sorry for bothering. Thank you for the quick reply and Merry Christmas!
