### ISSUE TITLE
hardware platform 

### ISSUE THREAD

**Issue by Chase-Fu** [jselbie/stunserver#60]
May I ask if this project supports ARM architecture

**Comment by jselbie** [comment]
Yes. 100%. If you need help compiling and installing let me know.

**Comment by Chase-Fu** [comment]
Can you tell me the steps for compilation and installation? Thank you very much!

**Comment by jselbie** [comment]
The instructions are in the README. You basically just download Boost,
unpack it.

Then in the Stunserver code, update the top line in the common.inc file in
the root directory to point to where you unpacked Boost.

Probably the only detail that needs to be updated is that latest Boost
version may not work. I think boost dropped support for pre C++11 builds.
That's ok, you can just manually download and unpack Boost 1.72 from: Index
of main/release/1.72.0/source (jfrog.io)
<https://boostorg.jfrog.io/artifactory/main/release/1.72.0/source/>

You don't actually need to build Boost. It just needs the sources.

After you download boost and update common.inc, you just type "make"

Why don't you try it and tell what happens

**Comment by Chase-Fu** [comment]
How to run a compiled client on a device using the OpenWrt system, but now the compiled arm client cannot run on OpenWrt

**Comment by jselbie** [comment]
@Chase-Fu  - you will need to elaborate the issue?

> but now the compiled arm client cannot run on OpenWrt

I don't know what you are doing. But I suspect you need to compile the code on the exact same platform as where you intend to run it. Compiling on version of Linux and hoping the binary runs exactly on another flavor of Linux has a lot of inherent difficulties. You can try static linking - as that might create a larger, but more compatible binary that will run on different systems.

**Comment by Chase-Fu** [comment]
Our goal is to run the stun-client on a small device with an aarch64 architecture. This device utilizes the OpenWrt system and due to limited hardware resources, it's unable to install a compilation toolchain. Currently, we aim to install a toolchain on an Ubuntu x86 machine using cross-compilation methods, compile the stun-client code, and generate a binary executable that can run on the aarch64 device. Do you have any suggestions? Thank you very much.

**Comment by jselbie** [comment]
Can you get a "hello world" type program to compile on the Ubuntu box and run on the OpenWRT box?

**Comment by Chase-Fu** [comment]
We have recompiled the source code according to the OpenWrt system's compilation method and dependency library, and it can be executed normally. Thank you for the author's support
