### ISSUE TITLE
All no-NAT connections are wrongly treated as Endpoint Independent Filtering by `CFilteringTest::PreRunCheck()`

### ISSUE THREAD

**Issue by ge9** [jselbie/stunserver#61]
Even when there is no NAT between client computers and the internet (i.e. the cllient has a global IP), there may be still a kind of filtering. For example, if an open port receives packets only from known [Address, Port], it should be treated as "Address and Port Dependent Filtering".
However, stunclient wrongly treats all of such no-NAT ("Direct Mapping") host as "Endpoint Independent Filtering", which is a mistake.

https://github.com/jselbie/stunserver/blob/d2d06a6d002d1e2fba312cf4993b08bb57a0346b/stuncore/stunclienttests.cpp#L344-L357

We should do nothing in this function.

**Comment by jselbie** [comment]
Thanks for reaching out. I agree - this function looks suspicious and is not in agreement with RFC 5780.

> 4.4 Determining NAT Filtering Behavior
> This will also require at most three tests.  These tests are sensitive to prior state on the NAT.

> In test I, the client performs the UDP connectivity test.  The server will return its alternate address and port in OTHER-ADDRESS in the binding response.  If OTHER-ADDRESS is not returned, the server does not support this usage and this test cannot be run.

> In test II, the client sends a binding request to the primary address of the server with the CHANGE-REQUEST attribute set to change-port and change-IP.  This will cause the server to send its response from its alternate IP address and alternate port.  If the client receives a response, the current behavior of the NAT is Endpoint-Independent Filtering.

> If no response is received, test III must be performed to distinguish between Address-Dependent Filtering and Address and Port-Dependent Filtering.  In test III, the client sends a binding request to the original server address with CHANGE-REQUEST set to change-port.  If the client receives a response, the current behavior is Address-Dependent Filtering; if no response is received, the current behavior is Address and Port-Dependent Filtering.

So the RFC stipulates that "test 2" must always be run unless test 1, the basic binding test, fails.  But for some reason, it's coded to end early on direct connections.

This might actually warrant an update to the code.

I'll try to post an update by Sunday night. There's a few more parts of the RFCs I want to research and check some old notes.

Thanks for bringing this to my attention

**Comment by jselbie** [comment]
I have a PR out for this: #62 
I'm going to test it more over the weekend and give this change some time to back. But if you want to help test it, much appreciated.

**Comment by ge9** [comment]
Thank you for quick update. I tested it now and it seems working correctly!
