### ISSUE TITLE
Nodejs Addon

### ISSUE THREAD

**Issue by formula1** [jselbie/stunserver#9]
This is an Enhancement

This server is clearly one of the best out there. However, creating a wrapper for it doesn't allow nearly as much control as having this server as a javascript object.

### Why?

* Because Authorization done in the javascript environment would be simpler for developers than doing it in c++
* Because using "native" javascript objects to start and stop the server is much kinder than running your framework within its own child process.

### What have I done?

I wrote some [psuedocode](https://gist.github.com/formula1/62cef83c97de8557a912) a while ago when I was trying to do it myself. However, my lack of c++ experience makes me worried I'll be spending a long time trying to learn the language rather than develop an application. Honestly, I don't like making requests because I know how requests feel. However, I also realize that if I never ask it may never happen. I also have taken a look at your code to see what would need to be changed, though I understood a reasonable amount of the low level aspects due to my Java experience I looked at things from a much higher level.

### My original Plan

This was the documentation I was attempting to base it off of
* http://nodejs.org/api/addons.html
* http://izs.me/v8-docs/classv8_1_1Value.html

After looking at your code, the files I believe that will need editing will be
* [main.cpp](https://github.com/jselbie/stunserver/blob/master/server/main.cpp) - Instead of getting CLI arguments, getting a v8 object.
* [auth.h and auth.cpp](http://nodejs.org/api/addons.html#addons_callbacks) - Authorization done in javascript could tie into the user system that is already in place

I understand if you're not interested in doing this. Just figured I'd mention it

**Comment by formula1** [comment]
So, I figured out where and why the segmenation fault was happening - http://stackoverflow.com/questions/12153998/how-do-i-use-v8-in-a-thread

A solution could be to unlock v8 when a new socket is created. This has taken me far longer than I wanted and since I have a far better understanding of how it works from a psuedocode/protocol standpoint I may start looking in that direction. You have been a really great help. Thank you for everything.

**Comment by jselbie** [comment]
I was feeling bad that I had not responded in a while.  Caught up in the
holidays.  Are you putting together a new pull request?

**Comment by formula1** [comment]
Sir, don't feel bad. I have been fully enjoying the holidays, though I probably would have enjoyed more working on this or other things. I was also been purposefully trying to keep your attention by being as active as I can be. 

Any pull request I can give is hardly progress unfortunately (though it took me a while to figure out this is the issue).

* This is my latest "working": https://github.com/formula1/stunserver/tree/auth
* This is my current "unstable": https://github.com/formula1/stunserver/tree/unstable

Both of which are unstable and neither working.

A solution may be [libuv's queue work](http://nikhilm.github.io/uvbook/threads.html#libuv-work-queue). Since thats what node runs in, its already available (libuv is how I keep the server alive now without running an infinite loop or a setInterval call [though technically what I am doing is a set interval call]). But my brain is pretty fried at the moment

**Comment by wtcross** [comment]
Having a node binding would make `stunserver` amazingly powerful/flexible in a lot of ways. Thank you for doing this work so far.

**Comment by formula1** [comment]
It's partly for selfish reasons of course, since I wanted it as well. But I feel lucky that this was created in the first place so I could attempt. It's tough advertising these types of projects as something that should be helped with. But I think anyone involved with serverside javascript would see this or a similar project as a convenient tool in the long run

**Comment by jselbie** [comment]
Closing out for now.  We can revisit node integration later.
